env:
  browser: true
  commonjs: true
  es6: true
  jest/globals: true
  node: true
extends:
  - 'eslint:recommended'
  - 'plugin:jest/recommended'
  - 'plugin:react/recommended'
parser: babel-eslint
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2018
  sourceType: module
plugins:
  - jest
  - react
rules:
  arrow-spacing:
    - error
  arrow-body-style:
    - error
  camelcase:
    - error
  class-methods-use-this:
    - error
  comma-dangle:
    - error
    - only-multiline
  complexity:
    - error
  consistent-return:
    - error
  curly:
    - error
  eol-last:
    - error
  eqeqeq:
    - error
  indent:
    - error
    - 2
  jsx-quotes:
    - error
  no-unused-expressions:
    - error
  no-multi-spaces:
    - error
  no-template-curly-in-string:
    - error
  no-trailing-spaces:
    - error
  prefer-arrow-callback:
    - error
  prefer-const:
    - error
  quotes:
    - error
    - single
  react/prefer-es6-class:
    - error
  react/prefer-stateless-function:
    - error
  semi:
    - error
    - never
  sort-keys:
    - error
  yoda:
    - error
    - never
settings:
  react:
    version: 16.5.0
